notifier:
  slack:
    token: "xoxb-XXXX"
    channel: "test-channel"
    template: |
      test format

feed:
  - url: https://example.com/feed1.xml
    auth:
      user: hogefuga
      pass: password
  - url: https://example.com/feed2.xml
