version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ryosan-470/rssnotify

    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -v
      - run: make test
      - run: ./.circleci/coverage.sh
      - run: bash <(curl -s https://codecov.io/bash)

  build_and_push:
    docker:
      - image: docker:18.04.0-ce-git
    environment:
      - TAG: jtwp470/rssnotify
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from ${TAG} -t ${TAG} .
      - deploy:
          name: Push to Docker Hub
          command: |
            docker push ${TAG}

workflows:
  version: 2
  test:
    jobs:
      - test
  build-and-push:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only:
                - master
